//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumboTCMS.WebFile.API._99bill {
    
    
    public partial class _default {
        
        ///E:/swf/ <summary>
        ///E:/swf/ Lab_orderId 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Label Lab_orderId;
        
        ///E:/swf/ <summary>
        ///E:/swf/ Lab_orderAmount 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Label Lab_orderAmount;
        
        ///E:/swf/ <summary>
        ///E:/swf/ Lab_payerName 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Label Lab_payerName;
        
        ///E:/swf/ <summary>
        ///E:/swf/ Lab_productName 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Label Lab_productName;
        
        ///E:/swf/ <summary>
        ///E:/swf/ inputCharset 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden inputCharset;
        
        ///E:/swf/ <summary>
        ///E:/swf/ bgUrl 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden bgUrl;
        
        ///E:/swf/ <summary>
        ///E:/swf/ version 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden version;
        
        ///E:/swf/ <summary>
        ///E:/swf/ language 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden language;
        
        ///E:/swf/ <summary>
        ///E:/swf/ signType 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden signType;
        
        ///E:/swf/ <summary>
        ///E:/swf/ signMsg 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden signMsg;
        
        ///E:/swf/ <summary>
        ///E:/swf/ merchantAcctId 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden merchantAcctId;
        
        ///E:/swf/ <summary>
        ///E:/swf/ payerName 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden payerName;
        
        ///E:/swf/ <summary>
        ///E:/swf/ payerContactType 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden payerContactType;
        
        ///E:/swf/ <summary>
        ///E:/swf/ payerContact 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden payerContact;
        
        ///E:/swf/ <summary>
        ///E:/swf/ orderId 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden orderId;
        
        ///E:/swf/ <summary>
        ///E:/swf/ orderAmount 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden orderAmount;
        
        ///E:/swf/ <summary>
        ///E:/swf/ orderTime 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden orderTime;
        
        ///E:/swf/ <summary>
        ///E:/swf/ productName 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden productName;
        
        ///E:/swf/ <summary>
        ///E:/swf/ productNum 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden productNum;
        
        ///E:/swf/ <summary>
        ///E:/swf/ productId 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden productId;
        
        ///E:/swf/ <summary>
        ///E:/swf/ productDesc 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden productDesc;
        
        ///E:/swf/ <summary>
        ///E:/swf/ ext1 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ext1;
        
        ///E:/swf/ <summary>
        ///E:/swf/ ext2 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden ext2;
        
        ///E:/swf/ <summary>
        ///E:/swf/ payType 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden payType;
        
        ///E:/swf/ <summary>
        ///E:/swf/ redoFlag 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden redoFlag;
        
        ///E:/swf/ <summary>
        ///E:/swf/ pid 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden pid;
    }
}
