//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1433
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumboTCMS.WebFile.User {
    
    
    public partial class _tougao_menulist {
        
        ///E:/swf/ <summary>
        ///E:/swf/ side 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl side;
    }
}
