//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5466
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumboTCMS.WebFile.Admin {
    
    
    public partial class _email_smtpserver_edit {
        
        ///E:/swf/ <summary>
        ///E:/swf/ form1 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtSmtpHost 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSmtpHost;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtSmtpPort 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSmtpPort;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtFromAddress 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFromAddress;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtFromName 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFromName;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtFromPwd 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFromPwd;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtToAddress 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtToAddress;
        
        ///E:/swf/ <summary>
        ///E:/swf/ btnSave 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
