//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumboTCMS.WebFile.Admin {
    
    
    public partial class _extend_qqonline_edit {
        
        ///E:/swf/ <summary>
        ///E:/swf/ form1 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtQQID 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtQQID;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtTitle 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtTColor 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTColor;
        
        ///E:/swf/ <summary>
        ///E:/swf/ rblFace 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rblFace;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtOrderNum 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtOrderNum;
        
        ///E:/swf/ <summary>
        ///E:/swf/ rblState 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.RadioButtonList rblState;
        
        ///E:/swf/ <summary>
        ///E:/swf/ btnSave 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
