//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3643
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JumboTCMS.WebFile.Admin {
    
    
    public partial class _module_article_collitem_edit {
        
        ///E:/swf/ <summary>
        ///E:/swf/ form1 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtTitle 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        
        ///E:/swf/ <summary>
        ///E:/swf/ ddlClassId 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlClassId;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtWebName 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtWebName;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtWebUrl 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtWebUrl;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtItemDemo 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtItemDemo;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtAuthor 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtAuthor;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtSourceFrom 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSourceFrom;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkIframe 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkIframe;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkObject 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkObject;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkScript 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkScript;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkDiv 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkDiv;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkTable 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkTable;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkSpan 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkSpan;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkImg 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkImg;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkFont 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkFont;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkA 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkA;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkHtml 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkHtml;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtCollecNewsNum 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCollecNewsNum;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkAutoChecked 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkAutoChecked;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkSaveFiles 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkSaveFiles;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkCollecOrder 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkCollecOrder;
        
        ///E:/swf/ <summary>
        ///E:/swf/ txtAutoCollectNum 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtAutoCollectNum;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkAutoChecked2 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkAutoChecked2;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkSaveFiles2 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkSaveFiles2;
        
        ///E:/swf/ <summary>
        ///E:/swf/ chkCollecOrder2 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.CheckBox chkCollecOrder2;
        
        ///E:/swf/ <summary>
        ///E:/swf/ ltAutoCollectHours 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Literal ltAutoCollectHours;
        
        ///E:/swf/ <summary>
        ///E:/swf/ btnSave 控件。
        ///E:/swf/ </summary>
        ///E:/swf/ <remarks>
        ///E:/swf/ 自动生成的字段。
        ///E:/swf/ 若要进行修改，请将字段声明从设计器文件移到代码隐藏文件。
        ///E:/swf/ </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;
    }
}
